spring.application.name=employee

spring.datasource.url=jdbc:postgresql://ep-super-star-aoffo3ee-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_r5GKes4RZIpO
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8999
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kpal53249@gmail.com
spring.mail.password=elcy dbfp wasm rutq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.main.allow-circular-references=true
